[theme]
primaryColor = "#e25d33"
backgroundColor = "#fdfaf6"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
port = 3000
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
